remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Lab 1: /lab1/lab1.html
  Lab 6: /lab6/lab6.html
  Project 1: /Project1/Project1.html
  Final Project: /finalproject/finalproject.html
  Defenders of Wildlife Internship: /Internship1/intern1.html
  
